<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('domain_dns_records', function (Blueprint $table) {
            $table->id();
            $table->foreignId('verified_domain_id')->constrained()->cascadeOnDelete();
            // Which of SendGrid's three dns.* keys this row mirrors -
            // deliberately NOT including a DMARC purpose here: SendGrid's
            // whitelabel/domains response never returns one (confirmed
            // against current docs), DMARC is a customer-managed DNS
            // policy record shown as a separate "recommended" step in the
            // wizard, never generated by us.
            $table->enum('record_purpose', ['mail_cname', 'dkim1', 'dkim2']);
            $table->string('type');
            $table->string('host');
            $table->text('data');
            $table->boolean('valid')->default(false);
            $table->timestamps();

            $table->unique(['verified_domain_id', 'record_purpose']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('domain_dns_records');
    }
};
